
[tasks."install"]
script = '''
cargo install --git=https://github.com/bytecodealliance/wasmtime.git cranelift-tools
'''

[tasks."run-clif"]
script = '''
clif-util run -v add.clif
'''

[tasks."compile-clif"]
# Ref.
# rustup component list
# https://github.com/bytecodealliance/wasmtime/blob/5c8bce70a11657ad6740f56a852f64d147f93494/cranelift/codegen/src/isa/mod.rs#L113C73-L113C80
script = '''
clif-util compile add.clif -o out.o --target x86_64-linux-android
clif-util compile add.clif -o out.o --target aarch64-apple-darwin
clif-util compile add.clif -o out.o --target s390x-unknown-linux-gnu
clif-util compile add.clif -o out.o --target riscv64gc-unknown-none-elf
'''

[tasks."run:jit"]
script = '''
cargo run --bin hi_jit
'''

[tasks."run:obj"]
script = '''
cargo run --bin toy
'''
